import {toCsv} from '../util/toCsv.js'
import { connectorOldDatabase } from '../db/connectorOldDatabase.js';

async function migracjaKlienci() {
    try {


await toCsv('WSP.CONTACT_ROLE','0.CONTACT_ROLE','0.CONTACT_ROLE')
await toCsv('WSP.IFS_CUSTOMER_INFO','1.IFS_CUSTOMER_INFO','1.IFS_CUSTOMER_INFO')
await toCsv('WSP.IFS_SUPPLIER_INFO_GENERAL','1.IFS_SUPPLIER_INFO_GENERAL','1.IFS_SUPPLIER_INFO_GENERAL')
await toCsv('PSZABAT.IFS_CUSTOMER_INFO_ADRESS_MIGR','2.IFS_CUSTOMER_INFO_ADRESS_MIGR','2.IFS_CUSTOMER_INFO_ADRESS_MIGR')
await toCsv('PSZABAT.IFS_SUPPLIER_INFO_ADRESS_MIGR','2.IFS_SUPPLIER_INFO_ADRESS_MIGR','2.IFS_SUPPLIER_INFO_ADRESS_MIGR')
await toCsv('PSZABAT.CUST_INFO_ADDRESS_TYPE','3.CUST_INFO_ADDRESS_TYPE','3.CUST_INFO_ADDRESS_TYPE')
await toCsv('PSZABAT.IFS_SUPPLIER_INFO_ADDRESS_TYPE','3.IFS_SUPPLIER_INFO_ADDRESS_TYPE','3.IFS_SUPPLIER_INFO_ADDRESS_TYPE')
await toCsv('PSZABAT.IFS_COMM_METHOD','4.IFS_COMM_METHOD','4.IFS_COMM_METHOD')
await toCsv('PSZABAT.IFS_COMM_METHOD_SUPPLIER','4.IFS_COMM_METHOD_SUPPLIER','4.IFS_COMM_METHOD_SUPPLIER')
await toCsv('PSZABAT.IFS_CUSTOMER_INFO_CONTACT','5.IFS_CUSTOMER_INFO_CONTACT','5.IFS_CUSTOMER_INFO_CONTACT')
await toCsv('PSZABAT.IFS_SUPPLIER_INFO_CONTACT','5.IFS_SUPPLIER_INFO_CONTACT','5.IFS_SUPPLIER_INFO_CONTACT')
await toCsv('PSZABAT.Cust_Ord_Customer','5.1.Cust_Ord_Customer','5.1.Cust_Ord_Customer-ZAD MIG PSZCRE_CUST_ORD_CUS')
await toCsv('PSZABAT.IFS_CUST_ORD_CUSTOMER_ENT','6.IFS_CUST_ORD_CUSTOMER_ENT','6.IFS_CUST_ORD_CUSTOMER_ENT')
await toCsv('PSZABAT.IFS_SUPPLIER','6.IFS_SUPPLIER','6.IFS_SUPPLIER')
await toCsv('PSZABAT.IDENTITY_INVOICE_INFO','10.IDENTITY_INVOICE_INFO','10.IDENTITY_INVOICE_INFO')
await toCsv('PSZABAT.IFS_SUPPLIER_ADDRESS_ENT','11.IFS_SUPPLIER_ADDRESS_ENT','11.IFS_SUPPLIER_ADDRESS_ENT')
await toCsv('PSZABAT.CUST_ORD_CUSTOMER_ADDRESS_ENT','11.CUST_ORD_CUSTOMER_ADDRESS_ENT','11.CUST_ORD_CUSTOMER_ADDRESS_ENT')
await toCsv('PSZABAT.SUPP_OUTBOUND_ADDR_INFO','11.SUPP_OUTBOUND_ADDR_INFO','11.SUPP_OUTBOUND_ADDR_INFO')
await toCsv('PSZABAT.IFS_INDENTITY_PAY_INFO','12.IFS_INDENTITY_PAY_INFO','12.IFS_INDENTITY_PAY_INFO')
await toCsv('PSZABAT.IFS_PAYMENT_WAY_PER_IDENTITY','12.IFS_PAYMENT_WAY_PER_IDENTITY','12.IFS_PAYMENT_WAY_PER_IDENTITY')
await toCsv('PSZABAT.IFS_SUPPLIER_TAX_INFO','13.IFS_SUPPLIER_TAX_INFO','13.IFS_SUPPLIER_TAX_INFO')
await toCsv('PSZABAT.IFS_TAX_ID_TYPE','13.IFS_TAX_ID_TYPE','13.IFS_TAX_ID_TYPE')
await toCsv('PSZABAT.PAYMENT_ADDRESS','13.PAYMENT_ADDRESS','13.PAYMENT_ADDRESS')
await toCsv('PSZABAT.IFS_SUPPLIER_DOCUMENT_TAX_INFO','14.IFS_SUPPLIER_DOCUMENT_TAX_INFO','14.IFS_SUPPLIER_DOCUMENT_TAX_INFO')
await toCsv('PSZABAT.IFS_CUSTOMER_TAX_INFO','15.IFS_CUSTOMER_TAX_INFO','15.IFS_CUSTOMER_TAX_INFO')
await toCsv('PSZABAT.IFS_CUSTOMER_TAX_FREE_TAX_CODE','16.IFS_CUSTOMER_TAX_FREE_TAX_CODE','16.IFS_CUSTOMER_TAX_FREE_TAX_CODE')
await toCsv('PSZABAT.IFS_CUSTOMER_TAX_FREE_TAX_CODE','17.IFS_CUSTOMER_TAX_FREE_TAX_CODE','17.IFS_CUSTOMER_TAX_FREE_TAX_CODE')
await toCsv('PSZABAT.IFS_CUSTOMER_DOCUMENT_TAX_INFO','18.IFS_CUSTOMER_DOCUMENT_TAX_INFO','18.IFS_CUSTOMER_DOCUMENT_TAX_INFO')
await toCsv('PSZABAT.FORWARDER_INFO','19.FORWARDER_INFO','19.FORWARDER_INFO')
await toCsv('PSZABAT.FORWARDER_INFO_ADDRESS','20.FORWARDER_INFO_ADDRESS','20.FORWARDER_INFO_ADDRESS')



console.log('KONIEC - MIGRACJA ZAKOŃCZONA')

} catch (error) {
    console.error('Error migracjaKlienci:', error);
}
}



migracjaKlienci();