import {toCsv} from '../util/toCsv.js'
import { connectorOldDatabase } from '../db/connectorOldDatabase.js';

async function migracjaProd() {
    try {

/*
await toCsv(connectorOldDatabase,'PSZABAT.IFS_DISCRETE_CHARACTERISTIC','1.DISCRETE_CHARACTERISTIC','1. Cecha dyskretna')
await toCsv(connectorOldDatabase,'PSZABAT.IFS_DISCRETE_CHARAC_VALUE','2.DISCRETE_CHARAC_VALUE','1. Cecha dyskretna')
await toCsv(connectorOldDatabase,'PSZABAT.IFS_CHARACTERISTIC_TEMPLATE','3.CHARACTERISTIC_TEMPLATE','1. Cecha dyskretna')
await toCsv(connectorOldDatabase,'PSZABAT.IFS_CHAR_TEMPL_DISCRETE_CHAR','4.CHAR_TEMPL_DISCRETE_CHAR','1. Cecha dyskretna')
*/

/*

await toCsv('PSZABAT.IFS_GRUPA_KOSZTOWA','1.PART_COST_GROUP','1. Grupa kosztowa pozycji')





await toCsv('PSZABAT.IFS_COMMODITY_GROUP','1.COMMODITY_GROUP','5. KOD GRUPY KOSZTOWEJ - commodity group')


await toCsv('PSZABAT.INPUT_UNIT_MEAS_GROUP','1.INPUT_UNIT_MEAS_GROUP','6. Grupy wejściowych J M')
await toCsv('PSZABAT.IFS_INPUT_UNIT_MEAS','2.IFS_INPUT_UNIT_MEAS','6. Grupy wejściowych J M')


// await toCsv('PSZABAT.POZ_GLOW','1.PART_CATALOG','6. Pozycja główna')
await toCsv('PSZABAT.POZ_GLOW_ZMIANA_ZEST','1.PART_CATALOG','6. Pozycja główna')



await toCsv('PSZABAT.PART_GTIN','1.PART_GTIN','6.1 . gtin ean Pozycja główna')



await toCsv('PSZABAT.STORAGE_CAPABILITY','1.STORAGE_CAPABILITY','6.1 Zdolność składowania')


// await toCsv('PSZABAT.IFS_POZYCJA_MAGAZYNOWA_TAB','1.INVENTORY_PART','7. Pozycja magazynowa')
await toCsv('PSZABAT.POZ_MAG_ZMIANA_ZEST','1.INVENTORY_PART','7. Pozycja magazynowa')




await toCsv('PSZABAT.IFS_SALES_PART','1.SALES_PART','7. Pozycja Sprzedażowa')
await toCsv('PSZABAT.SALES_PART_CROSS_REFERENCE','2.SALES_PART_CROSS_REFERENCE','7. Pozycja Sprzedażowa')
await toCsv('PSZABAT.SALES_PART_BASE_PRICE','3.SALES_PART_BASE_PRICE','7. Pozycja Sprzedażowa')
await toCsv('PSZABAT.SALES_PRICE_LIST_PART','4.SALES_PRICE_LIST_PART','7. Pozycja Sprzedażowa')

// await toCsv('PSZABAT.MANUF_PART_ATTRIBUTE','1.MANUF_PART_ATTRIBUTE','7.5 Pozycja magazynowa - produkcja')
await toCsv('PSZABAT.MANUF_PART_ATTRIBUTE_ZMI_ZEST','1.MANUF_PART_ATTRIBUTE','7.5 Pozycja magazynowa - produkcja')


await toCsv('PSZABAT.PURCHASE_PART','1.PURCHASE_PART','7. Pozycja Zakupowa')
await toCsv('PSZABAT.IFS_PURCHASE_PART_SUPPLIER','2.PURCHASE_PART_SUPPLIER','7. Pozycja Zakupowa')
*/

/*
await toCsv(connectorOldDatabase,'PSZABAT.INVENTORY_PART_CHAR_ALL','1.INVENTORY_PART_CHAR_ALL','8. Cechy pozycji magazynowej')
await toCsv(connectorOldDatabase,'PSZABAT.SALES_PART_CHARACTERISTIC','1.SALES_PART_CHARACTERISTIC','8. Cechy pozycji magazynowej')
*/
/*
await toCsv('PSZABAT.LABOR_CLASS','1.LABOR_CLASS','8.0 Kategorie zaszeregowania')



await toCsv('PSZABAT.IFS_WORK_CENTER','1.WORK_CENTER','8.1 Gniazdo produkcyjne')



await toCsv('PSZABAT.IFS_WORK_CENTER_RESOURCE','1.WORK_CENTER_RESOURCE','8.1 Gniazdo produkcyjne')
*/
await toCsv(connectorOldDatabase,'PSZABAT.DUMMY','1.WORK_CENTER_RESOURCE_updateWymaganyAleWidok.js','8.1 Gniazdo produkcyjne')
/*
await toCsv('PSZABAT.WORK_CENTER_RESOURCE','2.WORK_CENTER_RESOURCE_AVAIL','8.1 Gniazdo produkcyjne')
await toCsv('PSZABAT.WORK_CENTER_CHAR','3.WORK_CENTER_CHAR','8.1 Gniazdo produkcyjne')
*/

/*
await toCsv('PSZABAT.HANDLING_UNIT_CATEGORY','1.HANDLING_UNIT_CATEGORY','8.5 Kategorie jednostek obsługi')
await toCsv('PSZABAT.HANDLING_UNIT_TYPE','2.HANDLING_UNIT_TYPE','8.5 Kategorie jednostek obsługi')
*/

/*
await toCsv('WSP.V_IFS_TYPY_JO_MIG','0.HANDLING_UNIT_TYPE ','8.6 Instrukcje pakowania')
await toCsv('WSP.V_HANDLING_UNIT_ACCESSORY','1.HANDLING_UNIT_ACCESSORY','8.6 Instrukcje pakowania')
await toCsv('WSP.V_PACKING_INSTRUCTION','2.PACKING_INSTRUCTION','8.6 Instrukcje pakowania')
await toCsv('WSP.IFS_T_PACKING_INSTRUCTION_NODE','3.PACKING_INSTRUCTION_NODE','8.6 Instrukcje pakowania')
await toCsv('WSP.V_PACK_INSTR_NODE_ACCESSORY','4.PACK_INSTR_NODE_ACCESSORY','8.6 Instrukcje pakowania')
await toCsv('WSP.V_PART_HANDLING_UNIT','5.PART_HANDLING_UNIT','8.6 Instrukcje pakowania')





await toCsv('PSZABAT.WORK_CENTER_LOCATION','1.WORK_CENTER_LOCATION','9.1 Lokalizacje Gniazda prod')


await toCsv('PSZABAT.IFS_MARSZRUTA_FULL_UNION_HEAD','1.ROUTING_HEAD','10.3. Marszruta Full')
await toCsv('PSZABAT.ALTERNATE_FINAL_NEW_ALT','2.ROUTING_ALTERNATE','10.3. Marszruta Full')
await toCsv('PSZABAT.FINAL_OPERATIONS_NEW_ALT_TAB','3.ROUTING_OPERATION','10.3. Marszruta Full')

await toCsv('PSZABAT.SLOWNIK_WYDAJNOSCI_IFS','4. C_ROUTING_EFFICIENCY_CONF','10.3. Marszruta Full')
*/


//console.log('Memory usage after step :', process.memoryUsage());

/*
// await toCsv('PSZABAT.IFS_PROD_STRUCTURE_HEAD','1.PROD_STRUCTURE_HEAD','11. Struktura produktowa')
await toCsv(connectorOldDatabase,'PSZABAT.IFS_PROD_STRUCTURE_HEAD_ZMZEST','1.PROD_STRUCTURE_HEAD','11. Struktura produktowa')
// await toCsv('PSZABAT.IFS_PROD_STRUCT_ALTERNATE','2.PROD_STRUCT_ALTERNATE','11. Struktura produktowa')
await toCsv(connectorOldDatabase,'PSZABAT.IFS_PROD_STRUCT_ALTE_ZMZEST','2.PROD_STRUCT_ALTERNATE','11. Struktura produktowa')
// await toCsv('PSZABAT.IFS_PROD_STRUCTURE','3.PROD_STRUCTURE','11. Struktura produktowa')
await toCsv(connectorOldDatabase,'PSZABAT.IFS_PROD_STRUCTURE_ZMZEST','3.PROD_STRUCTURE','11. Struktura produktowa')
*/

//console.log('Memory usage after step :', process.memoryUsage());

/*
await toCsv('PSZABAT.IFS_MANUF_TOOL_TYPE','1.MANUF_TOOL_TYPE','12. Narzędzia produkcyjne')
// await toCsv('PSZABAT.IFS_MANUF_TOOL','2.MANUF_TOOL','12. Narzędzia produkcyjne')
await toCsv('PSZABAT.IFS_MANUF_TOOL_ZMZEST','2.MANUF_TOOL','12. Narzędzia produkcyjne')
await toCsv('PSZABAT.MANUF_TOOL_DETAIL','3.MANUF_TOOL_DETAIL','12. Narzędzia produkcyjne')
// await toCsv('PSZABAT.IFS_ROUTING_OPERATION_TOOL','4.ROUTING_OPERATION_TOOL','12. Narzędzia produkcyjne')
await toCsv('PSZABAT.IFS_ROUTING_OPER_TOL_ZMZEST','4.ROUTING_OPERATION_TOOL','12. Narzędzia produkcyjne')
// await toCsv('PSZABAT.C_TOOL_USAGE_CONDITION','5.C_TOOL_USAGE_CONDITION','12. Narzędzia produkcyjne')
await toCsv('PSZABAT.C_TOOL_USAGE_CONDITION_ZMZEST','5.C_TOOL_USAGE_CONDITION','12. Narzędzia produkcyjne')



await  toCsv('PSZABAT.ROUTING_OPER_WORK_GUIDE','1.ROUTING_OPER_WORK_GUIDE','12. Wytyczne rob Marszruta')


await  toCsv('PSZABAT.NORM_TYPE','1.NORM_TYPE','13. Typ wzorca')

*/






await toCsv(connectorOldDatabase, 'PSZABAT.IFS_QMAN_CONTROL_PLAN_PURCH','1.QMAN_CONTROL_PLAN_PURCH','14.Plany kontroli Plan Kontroli Zakupy')
await toCsv(connectorOldDatabase, 'PSZABAT.IFS_QMAN_CONL_PLAN_LIN_PURCH','2.QMAN_CONTROL_PLAN_LINE','14.Plany kontroli Plan Kontroli Zakupy')
/*
await toCsv(connectorOldDatabase, 'PSZABAT.C_QMAN_CTRL_PLAN_CODE','0.C_QMAN_CTRL_PLAN_CODE','14.Plan kontroli produkcja')
await toCsv(connectorOldDatabase, 'PSZABAT.IFS_QMAN_CONTROL_PLAN_MANUF','1.QMAN_CONTROL_PLAN_MANUF','14.Plan kontroli produkcja')
// await toCsv('PSZABAT.IFS_QMAN_CONTROL_PLAN_LINE','2.QMAN_CONTROL_PLAN_LINE','14.Plan kontroli produkcja') // FULL REKORDÓW
 await toCsv(connectorOldDatabase, 'PSZABAT.IFS_PLAN_LINE_PAGINATION_1','2.QMAN_CONTROL_PLAN_LINE_1','14.Plan kontroli produkcja') // PIERWSZE 1 MILION REKORDÓW
 await toCsv(connectorOldDatabase, 'PSZABAT.IFS_PLAN_LINE_PAGINATION_2','2.QMAN_CONTROL_PLAN_LINE_2','14.Plan kontroli produkcja') // POZNIEJSZE REKORDY DO 2 MILIONOW

await toCsv(connectorOldDatabase, 'PSZABAT.IFS_MANUF_TOOL_PLAN_KONTR','1.MANUF_TOOL','15. Narzedzia planu kontroli')
await toCsv(connectorOldDatabase, 'PSZABAT.MANUF_TOOL_DETAIL_PLAN_KONTR','2.MANUF_TOOL_DETAIL','15. Narzedzia planu kontroli')
await toCsv(connectorOldDatabase, 'PSZABAT.MANUF_TOOL_DETAIL_AVAIL_PLAN','2.MANUF_TOOL_DETAIL_AVAIL','15. Narzedzia planu kontroli')
await toCsv(connectorOldDatabase, 'PSZABAT.QMAN_CONTROL_PLAN_TOOLS','2.QMAN_CONTROL_PLAN_TOOLS','15. Narzedzia planu kontroli')
await toCsv(connectorOldDatabase, 'PSZABAT.QMAN_CONN_CTRL_PLAN_TOOLS','3.QMAN_CONN_CTRL_PLAN_TOOLS','15. Narzedzia planu kontroli')
*/

/*
// await toCsv('PSZABAT.INVENTORY_PART_PLANNING','1.INVENTORY_PART_PLANNING','16. Dane planistyczne poz. mag')
await toCsv('PSZABAT.INVENTORY_PART_PLANNING_ZMZEST','1.INVENTORY_PART_PLANNING','16. Dane planistyczne poz. mag')
*/

/*
await toCsv('PSZABAT.INVENTORY_LOCATION_GROUP','20.INVENTORY_LOCATION_GROUP','20. Grupy lokalizacji magazynowych')
await toCsv('PSZABAT.IFS_WAREHOUSE_LOKALIZACJE_MAG','21.IFS_WAREHOUSE_LOKALIZACJE_MAG','21. Magazyny')
await toCsv('PSZABAT.IFS_WAREHOUSE_BAY_LOK_MAG','22.WAREHOUSE_BAY_LOK_MAG','22. WAREHOUSE_BAY_LOK_MAG')
await toCsv('PSZABAT.IFS_WAREHOUSE_BAY_ROW_LOK_MAG','23.IFS_WAREHOUSE_BAY_ROW_LOK_MAG','22. IFS_WAREHOUSE_BAY_ROW_LOK_MAG')
await toCsv('PSZABAT.IFS_WAREHOUSE_BAY_ROW_LOK_MAG','23.IFS_WAREHOUSE_BAY_ROW_LOK_MAG','23. IFS_WAREHOUSE_BAY_ROW_LOK_MAG')
await toCsv('PSZABAT.IFS_WAREHOUSE_BAY_TIER_LOK_MAG','24.IFS_WAREHOUSE_BAY_TIER_LOK_MAG','24. IFS_WAREHOUSE_BAY_TIER_LOK_MAG')
await toCsv('PSZABAT.IFS_WAREHOUSE_BAY_BIN_LOK_MAG','25.IFS_WAREHOUSE_BAY_BIN_LOK_MAG','25. IFS_WAREHOUSE_BAY_BIN_LOK_MAG')
await toCsv('PSZABAT.WAREHOUSE_BIN_HU_CAPACITY','26.WAREHOUSE_BIN_HU_CAPACITY','26. WAREHOUSE_BIN_HU_CAPACITY')
await toCsv('PSZABAT.C_WAREHOUSE_SHIP_SETTINGS','27.C_WAREHOUSE_SHIP_SETTINGS','27. C_WAREHOUSE_SHIP_SETTINGS')
await toCsv('PSZABAT.WHSE_SHIPMENT_RECEIPT_INFO','28.PSZABAT.WHSE_SHIPMENT_RECEIPT_INFO','28. PSZABAT.WHSE_SHIPMENT_RECEIPT_INFO')
*/

/* Zmigrowanie przez WAJDZIAK
await toCsv('PSZABAT.IFS_WARUNK_PLATNOSCI','8. Warunki Płatnosci','26. FINANSE')
await toCsv('PSZABAT.PAYMENT_TERM_DETAILS','8. Warunki Płatnosci Szczegoly','26. FINANSE')
*/

/*
await toCsv('WSP.CONTACT_ROLE','0. CONTACT_ROLE','27. KLIENCI I DOSTAWCY')
await toCsv('WSP.IFS_CUSTOMER_INFO','1. CUSTOMER_INFO','27. KLIENCI I DOSTAWCY')
await toCsv('WSP.IFS_SUPPLIER_INFO_GENERAL','1. SUPPLIER_INFO','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.IFS_CUSTOMER_INFO_ADRESS_MIGR','2. CUSTOMER_INFO_ADDRESS','27. KLIENCI I DOSTAWCY')
await toCsv(' PSZABAT.IFS_SUPPLIER_INFO_ADRESS_MIGR','2. SUPPLIER_INFO_ADDRESS','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.CUSTOMER_INFO_OUR_ID_FIN_AUTH','2.3 CUSTOMER_INFO_OUR_ID_FIN_AUTH','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.SUPPLIER_INFO_OUR_ID_FIN_AUTH','2.4 SUPPLIER_INFO_OUR_ID_FIN_AUTH','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.CUST_INFO_ADDRESS_TYPE','3. CUSTOMER_INFO_ADDRESS_TYPE','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.IFS_SUPPLIER_INFO_ADDRESS_TYPE','3. SUPPLIER_INFO_ADDRESS_TYPE','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.IFS_COMM_METHOD','4. COMM_METHOD','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.IFS_COMM_METHOD_SUPPLIER','4. COMM_METHOD_SUPPLIER','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.IFS_OSOBY','4.5 PERSON_INFO_ALL','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.IFS_CUSTOMER_INFO_CONTACT','5. CUSTOMER_INFO_CONTACT','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.IFS_SUPPLIER_INFO_CONTACT','5. SUPPLIER_INFO_CONTACT','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.Cust_Ord_Customer','5.1 CUST_ORD_CUSTOMER','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.IFS_CUST_ORD_CUSTOMER_ENT','6. CUST_ORD_CUSTOMER_ENT','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.IFS_SUPPLIER','6. SUPPLIER','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.IDENTITY_INVOICE_INFO','10.IDENTITY_INVOICE_INFO','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.IFS_SUPPLIER_ADDRESS_ENT','11. SUPPLIER_ADDRESS_ENT','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.CUST_ORD_CUSTOMER_ADDRESS_ENT','11.CUST_ORD_CUSTOMER_ADDRESS_ENT','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.SUPP_OUTBOUND_ADDR_INFO','11.SUPP_OUTBOUND_ADDR_INFO','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.IFS_INDENTITY_PAY_INFO','12. IDENTITY_PAY_INFO','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.IFS_PAYMENT_WAY_PER_IDENTITY','12. PAYMENT_WAY_PER_IDENTITY','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.IFS_SUPPLIER_TAX_INFO','13. SUPPLIER_TAX_INFO','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.IFS_TAX_ID_TYPE','13. TAX_ID_TYPE','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.PAYMENT_ADDRESS','13.PAYMENT_ADDRESS','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.IFS_SUPPLIER_DOCUMENT_TAX_INFO','14. SUPPLIER_DOCUMENT_TAX_INFO','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.IFS_CUSTOMER_TAX_INFO','15. CUSTOMER_TAX_INFO','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.IFS_CUSTOMER_DELIVERY_TAX_INFO','16.CUSTOMER_DELIVERY_TAX_INFO','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.IFS_CUSTOMER_TAX_FREE_TAX_CODE','17. CUSTOMER_TAX_FREE_TAX_CODE','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.IFS_CUSTOMER_DOCUMENT_TAX_INFO','18. CUSTOMER_DOCUMENT_TAX_INFO','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.FORWARDER_INFO','10.5.FORWARDER_INFO','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.FORWARDER_INFO_ADDRESS','10.5.FORWARDER_INFO_ADDRESS','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.IFS_COMM_METHOD_FORWARDER','19.COMM_METHOD','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.DUMMY','8.CUSTOMER_GROUP','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.DUMMY','8.SUPPLIER_GROUP','27. KLIENCI I DOSTAWCY')
await toCsv('PSZABAT.DUMMY','9.INVOICE_PARTY_TYPE_GROUP','27. KLIENCI I DOSTAWCY')
*/





/*
await toCsv('PSZABAT.IFS_OSOBY','1.PERSON_INFO_ALL','33.OSOBY')
await toCsv('PSZABAT.IFSS_FND_USER','2.FND_USER','34.PRACOWNICY')
await toCsv('PSZABAT.USER_HANDLING_COMP_BY_USER','3.USER_HANDLING_COMP_BY_USER','34.PRACOWNICY')
await toCsv('PSZABAT.USER_DEFAULT','4.USER_DEFAULT','34.PRACOWNICY')
await toCsv('PSZABAT.USER_ALLOWED_STIE','5.USER_ALLOWED_STIE','34.PRACOWNICY')
await toCsv('PSZABAT.PERSON_COMPANY_ACCESS','6.PERSON_COMPANY_ACCESS','34.PRACOWNICY')
await toCsv('PSZABAT.COMPANY_EMP','7.COMPANY_EMP','34.PRACOWNICY')
*/


console.log('KONIEC - MIGRACJA ZAKOŃCZONA')

} catch (error) {
    console.error('Error migracjaProd:', error);
}
}



migracjaProd();