import {toApiRemove} from '../util/toApiRemove.js'
import { connectorOldDatabase } from "../db/connectorOldDatabase.js";
import {connectorCfg } from "../db/connectorCfg.js";
import {connectorTest } from "../db/connectorTest.js";
import {connectorProd } from "../db/connectorProd.js";
import { connectorXlsx } from '../db/connectorXlsx.js';



async function removerWybrana() {
    try {

  


// await toApiRemove(connectorXlsx,connectorProd,
//     `struktura pakowania kotwy - RAFAL BOCZKOWSKI`
//                     ,'PART_HANDLING_UNIT','PART_NO',1)    

// await toApiRemove(connectorXlsx,connectorProd,
//     `test-boczek`
//                     ,'PART_HANDLING_UNIT','PART_NO',1)    




// await toApiRemove(connectorXlsx,connectorCfg,
//     `PACK_INSTR_NODE_ACCESSORY BOCZKOWSKI`
//                     ,'PACK_INSTR_NODE_ACCESSORY','PACKING_INSTRUCTION_ID',1)   














await toApiRemove(connectorProd,connectorProd,
    `SELECT CONTRACT, PART_NO FROM INVENTORY_PART_CHAR_ALL WHERE CONTRACT = 'KRLAN' AND PART_NO IN
    
    (
    WITH CTE_01 AS (
select DISTINCT
T1.PART_NO AS PART_NO_1
,T1.description AS description_1
,T3.COMPONENT_PART AS CZY_STRUKTURA_PROD_1
,S1.part_no AS CZY_ZAPAS_1
,P1.PART_NO AS CZY_UZYTY_W_ZLEC_PROD_MATERIAL_1

,T2.PART_NO AS PART_NO_2
,T2.description AS description_2
,T4.COMPONENT_PART  AS CZY_STRUKTURA_PROD_2
,S2.part_no AS CZY_ZAPAS_2
,P2.PART_NO AS CZY_UZYTY_W_ZLEC_PROD_MATERIAL_2

FROM INVENTORY_PART T1
LEFT JOIN prod_structure T3 ON T3.COMPONENT_PART = T1.PART_NO
LEFT JOIN INVENTORY_PART_IN_STOCK_UIV S1 ON S1.part_no = T1.PART_NO
LEFT JOIN (SELECT DISTINCT part_no FROM SHOP_MATERIAL_ALLOC_UIV ) P1 ON P1.part_no = T1.PART_NO
 
JOIN INVENTORY_PART T2 ON T1.description = T2.description AND T1.PART_NO != T2.PART_NO
LEFT JOIN prod_structure T4 ON T4.COMPONENT_PART = T2.PART_NO
LEFT JOIN INVENTORY_PART_IN_STOCK_UIV S2 ON S2.part_no = T2.PART_NO 
LEFT JOIN (SELECT DISTINCT part_no FROM SHOP_MATERIAL_ALLOC_UIV ) P2 ON P2.part_no = T2.PART_NO

WHERE T1.CONTRACT = 'KRLAN'
AND T1.PRIME_COMMODITY IN 
(
'DRTLC'
,'DRTC'
,'WALC'
,'WAC1'
,'WAC2'
,'WU1C'
,'WU2C'
,'WU1EB'
,'WU2EB'
)

)

, CTE_02 AS (

SELECT
'KRLAN' AS CONTRACT
,T1.PART_NO_1
,T1.description_1
,T1.CZY_STRUKTURA_PROD_1
,T1.CZY_ZAPAS_1
,S1.qty_onhand AS ILE_NA_ZAPASIE_KG_1
,T1.CZY_UZYTY_W_ZLEC_PROD_MATERIAL_1

,T1.PART_NO_2
,T1.description_2
,T1.CZY_STRUKTURA_PROD_2
,T1.CZY_ZAPAS_2
,S2.qty_onhand  AS ILE_NA_ZAPASIE_KG_2
,T1.CZY_UZYTY_W_ZLEC_PROD_MATERIAL_2
FROM CTE_01 T1
LEFT JOIN (SELECT PART_NO, SUM(QTY_ONHAND) AS QTY_ONHAND  FROM INVENTORY_PART_IN_STOCK_UIV GROUP BY PART_NO) S1 ON S1.part_no = T1.PART_NO_1
LEFT JOIN (SELECT PART_NO, SUM(QTY_ONHAND) AS QTY_ONHAND  FROM INVENTORY_PART_IN_STOCK_UIV GROUP BY PART_NO)S2 ON S2.part_no = T1.PART_NO_2

 
order by t1.PART_NO_1

)
-- SELECT * FROM CTE_02

SELECT DISTINCT
PART_NO_1
FROM CTE_02
WHERE CZY_STRUKTURA_PROD_1 IS NULL
AND CZY_ZAPAS_1 IS NULL 
AND CZY_UZYTY_W_ZLEC_PROD_MATERIAL_1 IS NULL 
AND ILE_NA_ZAPASIE_KG_1 IS NULL

    
    
    )
    
    `
                    ,'INVENTORY_PART_CHAR','CONTRACT;PART_NO',1)   


await toApiRemove(connectorProd,connectorProd,
    `SELECT CONTRACT, PART_NO FROM PROD_STRUCTURE_HEAD WHERE CONTRACT = 'KRLAN' AND PART_NO IN
    (
    WITH CTE_01 AS (
select DISTINCT
T1.PART_NO AS PART_NO_1
,T1.description AS description_1
,T3.COMPONENT_PART AS CZY_STRUKTURA_PROD_1
,S1.part_no AS CZY_ZAPAS_1
,P1.PART_NO AS CZY_UZYTY_W_ZLEC_PROD_MATERIAL_1

,T2.PART_NO AS PART_NO_2
,T2.description AS description_2
,T4.COMPONENT_PART  AS CZY_STRUKTURA_PROD_2
,S2.part_no AS CZY_ZAPAS_2
,P2.PART_NO AS CZY_UZYTY_W_ZLEC_PROD_MATERIAL_2

FROM INVENTORY_PART T1
LEFT JOIN prod_structure T3 ON T3.COMPONENT_PART = T1.PART_NO
LEFT JOIN INVENTORY_PART_IN_STOCK_UIV S1 ON S1.part_no = T1.PART_NO
LEFT JOIN (SELECT DISTINCT part_no FROM SHOP_MATERIAL_ALLOC_UIV ) P1 ON P1.part_no = T1.PART_NO
 
JOIN INVENTORY_PART T2 ON T1.description = T2.description AND T1.PART_NO != T2.PART_NO
LEFT JOIN prod_structure T4 ON T4.COMPONENT_PART = T2.PART_NO
LEFT JOIN INVENTORY_PART_IN_STOCK_UIV S2 ON S2.part_no = T2.PART_NO 
LEFT JOIN (SELECT DISTINCT part_no FROM SHOP_MATERIAL_ALLOC_UIV ) P2 ON P2.part_no = T2.PART_NO

WHERE T1.CONTRACT = 'KRLAN'
AND T1.PRIME_COMMODITY IN 
(
'DRTLC'
,'DRTC'
,'WALC'
,'WAC1'
,'WAC2'
,'WU1C'
,'WU2C'
,'WU1EB'
,'WU2EB'
)

)

, CTE_02 AS (

SELECT
'KRLAN' AS CONTRACT
,T1.PART_NO_1
,T1.description_1
,T1.CZY_STRUKTURA_PROD_1
,T1.CZY_ZAPAS_1
,S1.qty_onhand AS ILE_NA_ZAPASIE_KG_1
,T1.CZY_UZYTY_W_ZLEC_PROD_MATERIAL_1

,T1.PART_NO_2
,T1.description_2
,T1.CZY_STRUKTURA_PROD_2
,T1.CZY_ZAPAS_2
,S2.qty_onhand  AS ILE_NA_ZAPASIE_KG_2
,T1.CZY_UZYTY_W_ZLEC_PROD_MATERIAL_2
FROM CTE_01 T1
LEFT JOIN (SELECT PART_NO, SUM(QTY_ONHAND) AS QTY_ONHAND  FROM INVENTORY_PART_IN_STOCK_UIV GROUP BY PART_NO) S1 ON S1.part_no = T1.PART_NO_1
LEFT JOIN (SELECT PART_NO, SUM(QTY_ONHAND) AS QTY_ONHAND  FROM INVENTORY_PART_IN_STOCK_UIV GROUP BY PART_NO)S2 ON S2.part_no = T1.PART_NO_2

 
order by t1.PART_NO_1

)
-- SELECT * FROM CTE_02

SELECT DISTINCT
PART_NO_1
FROM CTE_02
WHERE CZY_STRUKTURA_PROD_1 IS NULL
AND CZY_ZAPAS_1 IS NULL 
AND CZY_UZYTY_W_ZLEC_PROD_MATERIAL_1 IS NULL 
AND ILE_NA_ZAPASIE_KG_1 IS NULL

    
    )
    
    `
                    ,'PROD_STRUCTURE_HEAD','CONTRACT;PART_NO',1)   

await toApiRemove(connectorProd,connectorProd,
    `SELECT CONTRACT, PART_NO FROM INVENTORY_PART WHERE CONTRACT = 'KRLAN' AND PART_NO IN 
    (
    WITH CTE_01 AS (
select DISTINCT
T1.PART_NO AS PART_NO_1
,T1.description AS description_1
,T3.COMPONENT_PART AS CZY_STRUKTURA_PROD_1
,S1.part_no AS CZY_ZAPAS_1
,P1.PART_NO AS CZY_UZYTY_W_ZLEC_PROD_MATERIAL_1

,T2.PART_NO AS PART_NO_2
,T2.description AS description_2
,T4.COMPONENT_PART  AS CZY_STRUKTURA_PROD_2
,S2.part_no AS CZY_ZAPAS_2
,P2.PART_NO AS CZY_UZYTY_W_ZLEC_PROD_MATERIAL_2

FROM INVENTORY_PART T1
LEFT JOIN prod_structure T3 ON T3.COMPONENT_PART = T1.PART_NO
LEFT JOIN INVENTORY_PART_IN_STOCK_UIV S1 ON S1.part_no = T1.PART_NO
LEFT JOIN (SELECT DISTINCT part_no FROM SHOP_MATERIAL_ALLOC_UIV ) P1 ON P1.part_no = T1.PART_NO
 
JOIN INVENTORY_PART T2 ON T1.description = T2.description AND T1.PART_NO != T2.PART_NO
LEFT JOIN prod_structure T4 ON T4.COMPONENT_PART = T2.PART_NO
LEFT JOIN INVENTORY_PART_IN_STOCK_UIV S2 ON S2.part_no = T2.PART_NO 
LEFT JOIN (SELECT DISTINCT part_no FROM SHOP_MATERIAL_ALLOC_UIV ) P2 ON P2.part_no = T2.PART_NO

WHERE T1.CONTRACT = 'KRLAN'
AND T1.PRIME_COMMODITY IN 
(
'DRTLC'
,'DRTC'
,'WALC'
,'WAC1'
,'WAC2'
,'WU1C'
,'WU2C'
,'WU1EB'
,'WU2EB'
)

)

, CTE_02 AS (

SELECT
'KRLAN' AS CONTRACT
,T1.PART_NO_1
,T1.description_1
,T1.CZY_STRUKTURA_PROD_1
,T1.CZY_ZAPAS_1
,S1.qty_onhand AS ILE_NA_ZAPASIE_KG_1
,T1.CZY_UZYTY_W_ZLEC_PROD_MATERIAL_1

,T1.PART_NO_2
,T1.description_2
,T1.CZY_STRUKTURA_PROD_2
,T1.CZY_ZAPAS_2
,S2.qty_onhand  AS ILE_NA_ZAPASIE_KG_2
,T1.CZY_UZYTY_W_ZLEC_PROD_MATERIAL_2
FROM CTE_01 T1
LEFT JOIN (SELECT PART_NO, SUM(QTY_ONHAND) AS QTY_ONHAND  FROM INVENTORY_PART_IN_STOCK_UIV GROUP BY PART_NO) S1 ON S1.part_no = T1.PART_NO_1
LEFT JOIN (SELECT PART_NO, SUM(QTY_ONHAND) AS QTY_ONHAND  FROM INVENTORY_PART_IN_STOCK_UIV GROUP BY PART_NO)S2 ON S2.part_no = T1.PART_NO_2

 
order by t1.PART_NO_1

)
-- SELECT * FROM CTE_02

SELECT DISTINCT
PART_NO_1
FROM CTE_02
WHERE CZY_STRUKTURA_PROD_1 IS NULL
AND CZY_ZAPAS_1 IS NULL 
AND CZY_UZYTY_W_ZLEC_PROD_MATERIAL_1 IS NULL 
AND ILE_NA_ZAPASIE_KG_1 IS NULL

    
    
    )
    `
                    ,'INVENTORY_PART','CONTRACT;PART_NO',1)   
                    




await toApiRemove(connectorProd,connectorProd,
    `
SELECT 
T0.PART_NO
FROM PART_CATALOG T0
LEFT JOIN INVENTORY_PART T1 ON T0.part_no = T1.PART_NO AND T1.CONTRACT = 'KRLAN'
WHERE T0.description LIKE 'Drut%'
AND T1.PART_NO IS NULL
AND T0.part_no LIKE '1%'
    `
                    ,'PART_CATALOG','PART_NO',1)   


await toApiRemove(connectorProd,connectorProd,
    `
SELECT 
T0.PART_NO
FROM PART_CATALOG T0
LEFT JOIN INVENTORY_PART T1 ON T0.part_no = T1.PART_NO AND T1.CONTRACT = 'KRLAN'
WHERE T0.description LIKE 'Walc%'
AND T1.PART_NO IS NULL
AND T0.part_no LIKE '1%'
    `
                    ,'PART_CATALOG','PART_NO',1)   























// await toApiRemove(connectorProd,connectorProd,
//     `SELECT CONTRACT, PART_NO FROM INVENTORY_PART_CHAR_ALL WHERE CONTRACT = 'KRLAN' AND PART_NO IN
    
//     (
//     WITH CTE_01 AS (
// select DISTINCT
// T1.PART_NO AS PART_NO_1
// ,T1.description AS description_1
// ,T3.COMPONENT_PART AS CZY_STRUKTURA_PROD_1
// ,S1.part_no AS CZY_ZAPAS_1
// ,P1.PART_NO AS CZY_UZYTY_W_ZLEC_PROD_MATERIAL_1

// ,T2.PART_NO AS PART_NO_2
// ,T2.description AS description_2
// ,T4.COMPONENT_PART  AS CZY_STRUKTURA_PROD_2
// ,S2.part_no AS CZY_ZAPAS_2
// ,P2.PART_NO AS CZY_UZYTY_W_ZLEC_PROD_MATERIAL_2

// FROM INVENTORY_PART T1
// LEFT JOIN prod_structure T3 ON T3.COMPONENT_PART = T1.PART_NO
// LEFT JOIN INVENTORY_PART_IN_STOCK_UIV S1 ON S1.part_no = T1.PART_NO
// LEFT JOIN (SELECT DISTINCT part_no FROM SHOP_MATERIAL_ALLOC_UIV ) P1 ON P1.part_no = T1.PART_NO
 
// JOIN INVENTORY_PART T2 ON T1.description = T2.description AND T1.PART_NO != T2.PART_NO
// LEFT JOIN prod_structure T4 ON T4.COMPONENT_PART = T2.PART_NO
// LEFT JOIN INVENTORY_PART_IN_STOCK_UIV S2 ON S2.part_no = T2.PART_NO 
// LEFT JOIN (SELECT DISTINCT part_no FROM SHOP_MATERIAL_ALLOC_UIV ) P2 ON P2.part_no = T2.PART_NO

// WHERE T1.CONTRACT = 'KRLAN'
// AND T1.PRIME_COMMODITY IN 
// (
// 'DRTLC'
// ,'DRTC'
// ,'WALC'
// ,'WAC1'
// ,'WAC2'
// ,'WU1C'
// ,'WU2C'
// ,'WU1EB'
// ,'WU2EB'
// )

// )

// , CTE_02 AS (

// SELECT
// 'KRLAN' AS CONTRACT
// ,T1.PART_NO_1
// ,T1.description_1
// ,T1.CZY_STRUKTURA_PROD_1
// ,T1.CZY_ZAPAS_1
// ,S1.qty_onhand AS ILE_NA_ZAPASIE_KG_1
// ,T1.CZY_UZYTY_W_ZLEC_PROD_MATERIAL_1

// ,T1.PART_NO_2
// ,T1.description_2
// ,T1.CZY_STRUKTURA_PROD_2
// ,T1.CZY_ZAPAS_2
// ,S2.qty_onhand  AS ILE_NA_ZAPASIE_KG_2
// ,T1.CZY_UZYTY_W_ZLEC_PROD_MATERIAL_2
// FROM CTE_01 T1
// LEFT JOIN (SELECT PART_NO, SUM(QTY_ONHAND) AS QTY_ONHAND  FROM INVENTORY_PART_IN_STOCK_UIV GROUP BY PART_NO) S1 ON S1.part_no = T1.PART_NO_1
// LEFT JOIN (SELECT PART_NO, SUM(QTY_ONHAND) AS QTY_ONHAND  FROM INVENTORY_PART_IN_STOCK_UIV GROUP BY PART_NO)S2 ON S2.part_no = T1.PART_NO_2

 
// order by t1.PART_NO_1

// )
// -- SELECT * FROM CTE_02

// SELECT DISTINCT
// PART_NO_1
// FROM CTE_02
// WHERE CZY_STRUKTURA_PROD_1 IS NOT NULL
// AND CZY_ZAPAS_1 IS NULL 
// AND CZY_UZYTY_W_ZLEC_PROD_MATERIAL_1 IS NULL 
// AND ILE_NA_ZAPASIE_KG_1 IS NULL

    
    
//     )
    
//     `
//                     ,'INVENTORY_PART_CHAR','CONTRACT;PART_NO',1)   


// await toApiRemove(connectorProd,connectorProd,
//     `SELECT CONTRACT, PART_NO FROM PROD_STRUCTURE_HEAD WHERE CONTRACT = 'KRLAN' AND PART_NO IN
//     (
//     WITH CTE_01 AS (
// select DISTINCT
// T1.PART_NO AS PART_NO_1
// ,T1.description AS description_1
// ,T3.COMPONENT_PART AS CZY_STRUKTURA_PROD_1
// ,S1.part_no AS CZY_ZAPAS_1
// ,P1.PART_NO AS CZY_UZYTY_W_ZLEC_PROD_MATERIAL_1

// ,T2.PART_NO AS PART_NO_2
// ,T2.description AS description_2
// ,T4.COMPONENT_PART  AS CZY_STRUKTURA_PROD_2
// ,S2.part_no AS CZY_ZAPAS_2
// ,P2.PART_NO AS CZY_UZYTY_W_ZLEC_PROD_MATERIAL_2

// FROM INVENTORY_PART T1
// LEFT JOIN prod_structure T3 ON T3.COMPONENT_PART = T1.PART_NO
// LEFT JOIN INVENTORY_PART_IN_STOCK_UIV S1 ON S1.part_no = T1.PART_NO
// LEFT JOIN (SELECT DISTINCT part_no FROM SHOP_MATERIAL_ALLOC_UIV ) P1 ON P1.part_no = T1.PART_NO
 
// JOIN INVENTORY_PART T2 ON T1.description = T2.description AND T1.PART_NO != T2.PART_NO
// LEFT JOIN prod_structure T4 ON T4.COMPONENT_PART = T2.PART_NO
// LEFT JOIN INVENTORY_PART_IN_STOCK_UIV S2 ON S2.part_no = T2.PART_NO 
// LEFT JOIN (SELECT DISTINCT part_no FROM SHOP_MATERIAL_ALLOC_UIV ) P2 ON P2.part_no = T2.PART_NO

// WHERE T1.CONTRACT = 'KRLAN'
// AND T1.PRIME_COMMODITY IN 
// (
// 'DRTLC'
// ,'DRTC'
// ,'WALC'
// ,'WAC1'
// ,'WAC2'
// ,'WU1C'
// ,'WU2C'
// ,'WU1EB'
// ,'WU2EB'
// )

// )

// , CTE_02 AS (

// SELECT
// 'KRLAN' AS CONTRACT
// ,T1.PART_NO_1
// ,T1.description_1
// ,T1.CZY_STRUKTURA_PROD_1
// ,T1.CZY_ZAPAS_1
// ,S1.qty_onhand AS ILE_NA_ZAPASIE_KG_1
// ,T1.CZY_UZYTY_W_ZLEC_PROD_MATERIAL_1

// ,T1.PART_NO_2
// ,T1.description_2
// ,T1.CZY_STRUKTURA_PROD_2
// ,T1.CZY_ZAPAS_2
// ,S2.qty_onhand  AS ILE_NA_ZAPASIE_KG_2
// ,T1.CZY_UZYTY_W_ZLEC_PROD_MATERIAL_2
// FROM CTE_01 T1
// LEFT JOIN (SELECT PART_NO, SUM(QTY_ONHAND) AS QTY_ONHAND  FROM INVENTORY_PART_IN_STOCK_UIV GROUP BY PART_NO) S1 ON S1.part_no = T1.PART_NO_1
// LEFT JOIN (SELECT PART_NO, SUM(QTY_ONHAND) AS QTY_ONHAND  FROM INVENTORY_PART_IN_STOCK_UIV GROUP BY PART_NO)S2 ON S2.part_no = T1.PART_NO_2

 
// order by t1.PART_NO_1

// )
// -- SELECT * FROM CTE_02

// SELECT DISTINCT
// PART_NO_1
// FROM CTE_02
// WHERE CZY_STRUKTURA_PROD_1 IS NOT NULL
// AND CZY_ZAPAS_1 IS NULL 
// AND CZY_UZYTY_W_ZLEC_PROD_MATERIAL_1 IS NULL 
// AND ILE_NA_ZAPASIE_KG_1 IS NULL

    
//     )
    
//     `
//                     ,'PROD_STRUCTURE_HEAD','CONTRACT;PART_NO',1)   

// await toApiRemove(connectorProd,connectorProd,
//     `SELECT CONTRACT, PART_NO FROM INVENTORY_PART WHERE CONTRACT = 'KRLAN' AND PART_NO IN 
//     (
//     WITH CTE_01 AS (
// select DISTINCT
// T1.PART_NO AS PART_NO_1
// ,T1.description AS description_1
// ,T3.COMPONENT_PART AS CZY_STRUKTURA_PROD_1
// ,S1.part_no AS CZY_ZAPAS_1
// ,P1.PART_NO AS CZY_UZYTY_W_ZLEC_PROD_MATERIAL_1

// ,T2.PART_NO AS PART_NO_2
// ,T2.description AS description_2
// ,T4.COMPONENT_PART  AS CZY_STRUKTURA_PROD_2
// ,S2.part_no AS CZY_ZAPAS_2
// ,P2.PART_NO AS CZY_UZYTY_W_ZLEC_PROD_MATERIAL_2

// FROM INVENTORY_PART T1
// LEFT JOIN prod_structure T3 ON T3.COMPONENT_PART = T1.PART_NO
// LEFT JOIN INVENTORY_PART_IN_STOCK_UIV S1 ON S1.part_no = T1.PART_NO
// LEFT JOIN (SELECT DISTINCT part_no FROM SHOP_MATERIAL_ALLOC_UIV ) P1 ON P1.part_no = T1.PART_NO
 
// JOIN INVENTORY_PART T2 ON T1.description = T2.description AND T1.PART_NO != T2.PART_NO
// LEFT JOIN prod_structure T4 ON T4.COMPONENT_PART = T2.PART_NO
// LEFT JOIN INVENTORY_PART_IN_STOCK_UIV S2 ON S2.part_no = T2.PART_NO 
// LEFT JOIN (SELECT DISTINCT part_no FROM SHOP_MATERIAL_ALLOC_UIV ) P2 ON P2.part_no = T2.PART_NO

// WHERE T1.CONTRACT = 'KRLAN'
// AND T1.PRIME_COMMODITY IN 
// (
// 'DRTLC'
// ,'DRTC'
// ,'WALC'
// ,'WAC1'
// ,'WAC2'
// ,'WU1C'
// ,'WU2C'
// ,'WU1EB'
// ,'WU2EB'
// )

// )

// , CTE_02 AS (

// SELECT
// 'KRLAN' AS CONTRACT
// ,T1.PART_NO_1
// ,T1.description_1
// ,T1.CZY_STRUKTURA_PROD_1
// ,T1.CZY_ZAPAS_1
// ,S1.qty_onhand AS ILE_NA_ZAPASIE_KG_1
// ,T1.CZY_UZYTY_W_ZLEC_PROD_MATERIAL_1

// ,T1.PART_NO_2
// ,T1.description_2
// ,T1.CZY_STRUKTURA_PROD_2
// ,T1.CZY_ZAPAS_2
// ,S2.qty_onhand  AS ILE_NA_ZAPASIE_KG_2
// ,T1.CZY_UZYTY_W_ZLEC_PROD_MATERIAL_2
// FROM CTE_01 T1
// LEFT JOIN (SELECT PART_NO, SUM(QTY_ONHAND) AS QTY_ONHAND  FROM INVENTORY_PART_IN_STOCK_UIV GROUP BY PART_NO) S1 ON S1.part_no = T1.PART_NO_1
// LEFT JOIN (SELECT PART_NO, SUM(QTY_ONHAND) AS QTY_ONHAND  FROM INVENTORY_PART_IN_STOCK_UIV GROUP BY PART_NO)S2 ON S2.part_no = T1.PART_NO_2

 
// order by t1.PART_NO_1

// )
// -- SELECT * FROM CTE_02

// SELECT DISTINCT
// PART_NO_1
// FROM CTE_02
// WHERE CZY_STRUKTURA_PROD_1 IS NOT NULL
// AND CZY_ZAPAS_1 IS NULL 
// AND CZY_UZYTY_W_ZLEC_PROD_MATERIAL_1 IS NULL 
// AND ILE_NA_ZAPASIE_KG_1 IS NULL

    
    
//     )
//     `
//                     ,'INVENTORY_PART','CONTRACT;PART_NO',1)   
                    




// await toApiRemove(connectorProd,connectorProd,
//     `
// SELECT 
// T0.PART_NO
// FROM PART_CATALOG T0
// LEFT JOIN INVENTORY_PART T1 ON T0.part_no = T1.PART_NO AND T1.CONTRACT = 'KRLAN'
// WHERE T0.description LIKE 'Drut%'
// AND T1.PART_NO IS NULL
// AND T0.part_no LIKE '1%'
//     `
//                     ,'PART_CATALOG','PART_NO',1)   


// await toApiRemove(connectorProd,connectorProd,
//     `
// SELECT 
// T0.PART_NO
// FROM PART_CATALOG T0
// LEFT JOIN INVENTORY_PART T1 ON T0.part_no = T1.PART_NO AND T1.CONTRACT = 'KRLAN'
// WHERE T0.description LIKE 'Walc%'
// AND T1.PART_NO IS NULL
// AND T0.part_no LIKE '1%'
//     `
//                     ,'PART_CATALOG','PART_NO',1)   










} catch (error) {
    console.error('Error occurred during execution:', error);
}
}



removerWybrana()